### ISSUE TITLE
Rendering grid data

### ISSUE THREAD

**Issue by tupaje1** [flexicious/flxs-webcomponents-tree-grid#1]
The data is not displaying in the grid when the grid becomes visible on the screen. 

On initial load of the view, the grid is not displayed on the screen and the height and width is set to 0 by default and the data for the grid is set to the dataProvider. But after the user clicks on the toggle button, iron-pages will switch the the grid view and the height and width of the content area and grid will dynamically adjusted to fill the area but no data is displayed.

I verified that the data is set on the dataProvider. Is there way to rerun the grid only when there is data in the dataProvider and the height and width changes from the default width and height of 0 .

**Comment by tupaje1** [comment]
The bug fix did not resolve the issue. In the pull request, I added a second demo example which replicates the rendering grid data. Can you take a look at that and see if you can come up with a fix for that?

**Comment by tupaje1** [comment]
Thanks for the fix you added. When you have a change, can you consider using https://www.webcomponents.org/element/PolymerElements/iron-resizable-behavior to help with coordinating the flow of resize events.

**Comment by flexicious** [comment]
Added iron-resize support
