### ISSUE TITLE
Styling of icons buttons on toolbar

### ISSUE THREAD

**Issue by tupaje1** [flexicious/flxs-webcomponents-tree-grid#11]
How can we set the background color and padding of the toolbar button?

**Comment by flexicious** [comment]
You can either use CSS, or you can create a custom toolbar
https://github.com/flexicious/flxs-webcomponents-tree-grid/blob/master/demo/customscreens/CustomPagerControlAS.js

http://blog.htmltreegrid.com/post/How-to-Customize-the-Pager-(Toolbar)-Export-Options-Settings-and-Save-Settings-Popups.aspx
