### ISSUE TITLE
Option to change the order of the buttons that appear in the toolbar

### ISSUE THREAD

**Issue by tupaje1** [flexicious/flxs-webcomponents-tree-grid#12]
Is there a way to change the order of the buttons that appear in the toolbar?
For eg: from left to right Refresh button, Filter buttons, and then the Star/Settings button

**Comment by flexicious** [comment]
https://github.com/flexicious/flxs-webcomponents-tree-grid/blob/master/demo/customscreens/CustomPagerControlAS.js

**Comment by flexicious** [comment]
https://github.com/flexicious/flxs-webcomponents-tree-grid/commit/5eb5d462ed949357a8886bbac8febc64e078d7e6

Example added

**Comment by flexicious** [comment]
https://github.com/flexicious/flxs-webcomponents-tree-grid/commit/5eb5d462ed949357a8886bbac8febc64e078d7e6
