### ISSUE TITLE
I have a hierarchical grid and ONE of the groups need to be expanded by default.

### ISSUE THREAD

**Issue by Thuthinh** [flexicious/flxs-webcomponents-tree-grid#28]
I have a hierarchical grid and ONE of the groups need to be expanded by default.
Is this possible to accomplish with data binding? or do I need to use the API to accomplish this?
Thanks in advance.

**Comment by flexicious** [comment]
Need to use expandChildrenOf method. Once grid has dataprovider and built, you can call 
grid.validateNow()
grid.expandChildrenOf(yourDataProvider[0])
