### ISSUE TITLE
Group Headers grid lines are added back when using the grid.collapseAll() in the CustomPagerControl.

### ISSUE THREAD

**Issue by Jonny-Nguyen** [flexicious/flxs-webcomponents-tree-grid#35]
CustomPagerControl doesn't know about the cellBackGroundColor function when executing the grid.collapseAll();

**Comment by flexicioussupport** [comment]
This issue not reproduced again.
![img_30062017_183500_1](https://user-images.githubusercontent.com/29047802/27736886-a8c16224-5dc3-11e7-9d17-0b4dace9e949.png)
![img_30062017_183500_0](https://user-images.githubusercontent.com/29047802/27736885-a8be3248-5dc3-11e7-8e53-91747c8c5198.png)

**Comment by flexicioussupport** [comment]
Check this example.
[hierarchical-grid-column-group.zip](https://github.com/flexicious/flxs-webcomponents-tree-grid/files/1115280/hierarchical-grid-column-group.zip)

**Comment by Jonny-Nguyen** [comment]
This issue have not been resolved. When use the expandAll and collapseAll the border for the child element is applied to the group element.

**Comment by flexicious** [comment]
We are not able to reproduce this issue - please make sure you have latest flxs files. Please provide a test file we can use to reproduce the issue
