### ISSUE TITLE
hierarchical grid need single item select and style the border to highlight the open group section 

### ISSUE THREAD

**Issue by Jonny-Nguyen** [flexicious/flxs-webcomponents-tree-grid#39]
Only one item can be selected at any given time.
When group is in expended mode need way to set the border of the last item.

**Comment by flexicious** [comment]
https://github.com/flexicioussupport/flxs-webcomponents-tree-grid/blob/8ce6fc8a00075236927326e2105f35fa058a93ce/demo/hierarchical-grid-column-group.html

This is working for us. Please get latest and confirn.

**Comment by flexicious** [comment]
Can you please provide a screenshot of what you are looking for

**Comment by Jonny-Nguyen** [comment]
Only one row can be selected at any given time and the group line can not be selected.

**Comment by flexicious** [comment]
If you want to disable selection at parent level please use rowSelectableFunction

If you want to have only one row selected, please use selectionMode=singleRow

**Comment by flexicious** [comment]
If you want to disable selection at parent level please use rowSelectableFunction
http://www.htmltreegrid.com/demo/prod_jq_treegrid.html?example=Grouped Data2

If you want to have only one row selected, please use selectionMode=singleRow
http://www.htmltreegrid.com/demo/prod_jq_treegrid.html?example=Selection Modes
