### ISSUE TITLE
Please review https://github.com/flexicious/flxs-webcomponents-tree-grid/issues/35

### ISSUE THREAD

**Issue by Jonny-Nguyen** [flexicious/flxs-webcomponents-tree-grid#40]
The suggested solution will not resolve the issue at hand. Please review it and let me know if you have any questions.

https://github.com/flexicious/flxs-webcomponents-tree-grid/issues/35.

**Comment by flexicious** [comment]
Please provide screenshot ando reproducible test cae.

**Comment by flexicious** [comment]
https://github.com/flexicioussupport/flxs-webcomponents-tree-grid/blob/8ce6fc8a00075236927326e2105f35fa058a93ce/demo/hierarchical-grid-column-group.html

This is working for us. Please get latest and confirm.
