### ISSUE TITLE
Need a way to highlight individual cell and select.

### ISSUE THREAD

**Issue by Jonny-Nguyen** [flexicious/flxs-webcomponents-tree-grid#42]
Need a way to highlight individual cell and select.

**Comment by flexicious** [comment]
to highlight cell use
highlightRow method

http://htmltreegrid.com/docs/class/js/flexgrid/grids/FlexDataGrid.js~FlexDataGrid.html#instance-method-highlightRow

To select a row please use 
http://htmltreegrid.com/docs/class/js/flexgrid/grids/FlexDataGrid.js~FlexDataGrid.html#instance-method-addSelectedItem
If row is at inner level please use
http://htmltreegrid.com/docs/class/js/flexgrid/grids/FlexDataGridColumnLevel.js~FlexDataGridColumnLevel.html#instance-method-addSelectedItem
