### ISSUE TITLE
Need to style the filter input box on the grid

### ISSUE THREAD

**Issue by Jonny-Nguyen** [flexicious/flxs-webcomponents-tree-grid#51]
Need to style the filter input box on the grid

**Comment by flexicious** [comment]
Use css. 

https://github.com/flexicious/flxs-webcomponents-tree-grid/blob/master/flxs-tree-grid-styles.html



.flexiciousGrid input {
--
  | overflow: hidden;
  | white-space: nowrap;
  | padding: 0px;
  | margin: 0px;
  | cursor: default;
  | }
  |  
  | .flexiciousGrid .TextInput {
  | position: relative;
  | }
