### ISSUE TITLE
Disabled selecting or highlighting the group row.

### ISSUE THREAD

**Issue by Jonny-Nguyen** [flexicious/flxs-webcomponents-tree-grid#52]
Disabled selecting and highlighting the group row.

**Comment by Jonny-Nguyen** [comment]
Please respond if the requirements are not cleared.

**Comment by flexicious** [comment]
You can disable selection at any level:
http://www.htmltreegrid.com/demo/prod_jq_treegrid.html?example=Grouped%20Data2

Please see 
rowSelectableFunction
http://www.htmltreegrid.com/demo/examples/js/samples/GroupedData2.js


http://htmltreegrid.com/docs/class/js/flexgrid/grids/FlexDataGridColumnLevel.js~FlexDataGridColumnLevel.html#instance-member-rowSelectableFunction
