### ISSUE TITLE
Need a way to put a border at the bottom of each group in expand mode.

### ISSUE THREAD

**Issue by Jonny-Nguyen** [flexicious/flxs-webcomponents-tree-grid#53]
Need a way to put a border at the bottom of each group in expand mode.

**Comment by flexicious** [comment]
It seems to be doing that - please confirm what you need.

![image](https://user-images.githubusercontent.com/6350967/28487747-ebcc4374-6e65-11e7-9d45-3191c7ff5be7.png)
