### ISSUE TITLE
Need to display "..." when column is width is smaller than actual text inside the cell

### ISSUE THREAD

**Issue by Jonny-Nguyen** [flexicious/flxs-webcomponents-tree-grid#55]
1. Need to display "..." when column is width is smaller than actual text inside the cell.
2. Also need to add title property to the cell so on hover user will get all the information.

**Comment by flexicious** [comment]
please use truncateToFit
example
http://www.htmltreegrid.com/demo/prod_jq_treegrid.html?example=Simple
Docs
http://htmltreegrid.com/docs/class/js/flexgrid/grids/FlexDataGridColumn.js~FlexDataGridColumn.html#instance-member-truncateToFit

**Comment by flexicious** [comment]
You cannot have both trunaceToFit and vertical center align text. If you want to use truncateToFit remove this section from you styles:

            .flexiciousGrid .flexDataGridVirtualBodyContainer .flexDataGridDataCell .cellRenderer {
                display: flex;
                align-items: center;
            }

**Comment by flexicious** [comment]
You can get it to center align with single line text like this instead of using flex model:
            .flexiciousGrid .flexDataGridVirtualBodyContainer .flexDataGridDataCell label {
                margin-top:4px;
            }

**Comment by Jonny-Nguyen** [comment]
I am still having issues. I don't have the mention call at all. I have headerAlign=center but my textAlign = left. Please advise.

**Comment by flexicious** [comment]
https://github.com/flexicious/flxs-webcomponents-tree-grid/commit/ec9808b7fd8207b5da18f6c25d3b28ea7582f0cd

**Comment by flexicious** [comment]
please get latest

**Comment by Jonny-Nguyen** [comment]
I am still having issue can you setup a webex meeting to get this resolved?

**Comment by flexicious** [comment]
http://localhost:8081/components/flxs-tree-grid/demo/variable-header-height.html

![image](https://user-images.githubusercontent.com/6350967/28628107-ab8e3ee0-71f1-11e7-9c6c-8115cc351004.png)
