### ISSUE TITLE
Need to allow MultiSelectCombobox on filter

### ISSUE THREAD

**Issue by Jonny-Nguyen** [flexicious/flxs-webcomponents-tree-grid#56]
I am enable to apply MultiSelectCombobox on column but the dropdown show checkbox with empty text. Please provide a demo.

**Comment by flexicioussupport** [comment]
You have to set  filterComboBoxBuildFromGrid="true"

![img_03082017_162842_0](https://user-images.githubusercontent.com/29047802/28918971-18655bd4-7869-11e7-95a6-af3b95f93f62.png)
[example.zip](https://github.com/flexicious/flxs-webcomponents-tree-grid/files/1196927/example.zip)

**Comment by Jonny-Nguyen** [comment]
Its working now but I need to style this component. Please provide the CSS to style the popup

**Comment by flexicious** [comment]
It in 
https://github.com/flexicious/flxs-webcomponents-tree-grid/blob/master/flxs-tree-grid-styles.html

/*=============multiselect combobox ===================*/
            
            .flexiciousGrid .multiSelectComboBox {
                display: inline-block;
            }
            
            .flexiciousGrid .multiSelectComboBox .textBox {
                top: 2px;
            }
            
            .flexiciousGrid .multiSelectComboBox img {
                top: 2px;
            }
            
            .flexiciousGrid .multiSelectComboBoxPopup {
                border: solid 1px black;
                background: white;
                z-index: 1001;
            }
            
            .flexiciousGrid .multiSelectComboBoxPopup .checkBoxRow {
                padding: 2px;
            }
            
            .flexiciousGrid .multiSelectComboBoxPopup .okCancelDiv {
                display: block;
            }
            
            .flexiciousGrid .multiSelectComboBoxPopup .okCancel {
                padding: 4px;
                text-align: right;
                border-top: solid 1px #CCCCCC;
            }
            
            .flexiciousGrid .multiSelectComboBoxPopup .okButton {
                padding: 2px;
                text-decoration: underline;
                cursor: pointer;
                display: inline;
            }
            
            .flexiciousGrid .multiSelectComboBoxPopup .cancelButton {
                padding: 2px;
                text-decoration: underline;
                cursor: pointer;
                display: inline;
            }
            
            .flexiciousGrid .multiSelectComboBoxPopup .hover {
                background: #CEDBEF;
            }
