### ISSUE TITLE
Why is NONE show up as a dropdown option when using combo as filter

### ISSUE THREAD

**Issue by Jonny-Nguyen** [flexicious/flxs-webcomponents-tree-grid#57]
Also what is the reason behind the NONE option. It looks like it gives the same behavior as ALL option in the dropdown filter on column header.

**Comment by flexicious** [comment]
None shows up because there might be items with no value for that column. This only works if you set useLabelFunctionForFilterCompare to true. If you dont want none, just set blankValuesLabel property on datagrid column to empty string.

**Comment by flexicious** [comment]
Please run this

https://github.com/flexicious/flxs-webcomponents-tree-grid/blob/f1c2b60a07d96cc0ce3451bae33e13be32f6fc60/demo/basic-grid-MultiSelectComboBox-filter.html
